### ISSUE TITLE
Where is this code from ?

### ISSUE THREAD

**Issue by fcantournet** [elestranobaron/T4C-Serveur-Multiplateformes#1]
I was browsing through the code, mostly to understand so game mecanism better and I was wondering how close to actual code from official servers this is ?

Is this codebase related to the official codebase or a pure re-implementation ?

**Comment by sebastien-desbois** [comment]
Looks to me as an extracted base from the official source tree.

**Comment by elestranobaron** [comment]
Bonjour.

Ce code vient des derniers détenteurs de la licence.

Hopefully aussi proch de la 1.25 que possible.

**Comment by elestranobaron** [comment]
Apres ce que je suis en train de faire c'est apporter des vrais fonctions linux telles que pthread en lieu et place de l'implementation windows, afin de pouvoir compiler ce serveur sous linux.

**Comment by gabriel-robert** [comment]
Nice, j'y jetterai un œil.
Par hasard, des sources du client 1.25 qui traînent? J'aimerais l'adapter pour fonctionner sur des systèmes récent, a minima avec une VM, au mieux avec Wine/Proton

**Comment by NewbiZ** [comment]
Est-ce que tu aurais encore le code original par hasard ?
