### ISSUE TITLE
Original sources

### ISSUE THREAD

**Issue by galetan71** [elestranobaron/T4C-Serveur-Multiplateformes#3]
Hello.

Is-it possible to send the original sources to compare with your version ?
It is hard to see what you ve done.
For example when I edit Lock.h il can see the pthread processes but i can't compare with the origal one.

Thank you.

**Comment by NewbiZ** [comment]
Up,

I'm also interested in the original code :-)

**Comment by elestranobaron** [comment]
Original serveur https://github.com/elestranobaron/Server

Egalement l' original client https://github.com/elestranobaron/Client
